# Generated by Django 6.0.8 on 2026-09-11 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.BigIntegerField()),
                ("finished_at", models.BigIntegerField(null=True)),
                ("model", models.TextField()),
                ("reasoning", models.TextField()),
                ("message_count", models.IntegerField()),
                ("status", models.CharField(max_length=20)),
                ("response_id", models.TextField(null=True)),
                ("input_tokens", models.BigIntegerField(null=True)),
                ("cached_tokens", models.BigIntegerField(null=True)),
                ("cache_write_tokens", models.BigIntegerField(null=True)),
                ("output_tokens", models.BigIntegerField(null=True)),
                ("reasoning_tokens", models.BigIntegerField(null=True)),
                ("cost_usd", models.FloatField(null=True)),
                ("pricing", models.JSONField(null=True)),
                ("error_kind", models.CharField(max_length=60, null=True)),
            ],
            options={
                "db_table": "ai_requests",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("thread_id", models.TextField()),
                ("sender", models.TextField()),
                ("subject", models.TextField()),
                ("received_at", models.BigIntegerField(db_index=True)),
                ("labels", models.JSONField(default=list)),
                ("body", models.TextField(null=True)),
                ("unsubscribe", models.TextField(null=True)),
            ],
            options={
                "db_table": "messages",
                "ordering": ("-received_at", "id"),
            },
        ),
        migrations.CreateModel(
            name="Sender",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("note", models.TextField(db_default="", default="")),
            ],
            options={
                "db_table": "senders",
            },
        ),
        migrations.CreateModel(
            name="Tab",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=225)),
                ("query", models.TextField(db_default="", default="")),
                ("label_id", models.TextField(null=True, unique=True)),
                ("description", models.TextField(db_default="", default="")),
                ("people", models.JSONField(db_default=[], default=list)),
                ("auto_classify", models.BooleanField(db_default=False, default=False)),
                ("position", models.IntegerField(db_default=0, default=0)),
            ],
            options={
                "db_table": "tabs",
                "ordering": ("position", "id"),
            },
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "kind",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("task_id", models.CharField(max_length=36, null=True)),
                ("generation", models.PositiveIntegerField(default=0)),
                ("retry_ai", models.BooleanField(default=False)),
                ("progress", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.IntegerField(default=1, primary_key=True, serialize=False),
                ),
                ("email", models.EmailField(max_length=254)),
                ("history_id", models.TextField(null=True)),
                ("synced_at", models.BigIntegerField(null=True)),
            ],
            options={
                "db_table": "account",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="one_account"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AITracking",
            fields=[
                (
                    "id",
                    models.IntegerField(default=1, primary_key=True, serialize=False),
                ),
                ("started_at", models.BigIntegerField()),
            ],
            options={
                "db_table": "ai_tracking",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="one_tracking_start"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="inbox.message",
                    ),
                ),
                ("policy", models.TextField()),
            ],
            options={
                "db_table": "classifications",
            },
        ),
        migrations.CreateModel(
            name="LabelDecision",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "message_id",
                        "label_id",
                        "source",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label_id", models.TextField()),
                ("source", models.CharField(max_length=16)),
                ("reason", models.TextField()),
                ("applied", models.BooleanField(db_default=False, default=False)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inbox.message"
                    ),
                ),
            ],
            options={
                "db_table": "label_decisions",
            },
        ),
    ]
