# Generated by Django 6.0.8 on 2026-09-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0003_split_model_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="recipients",
            field=models.JSONField(null=True),
        ),
    ]
