# Generated by Django 6.0.8 on 2026-09-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0007_message_ai_classified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="labels",
            field=models.JSONField(
                default=list,
                help_text="Cached Gmail label IDs, refreshed by sync and successful app label writes.",
            ),
        ),
    ]
