# Generated by Django 6.0.8 on 2026-09-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0008_delete_legacyimport_alter_message_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="in_ai_window",
            field=models.BooleanField(
                db_default=False,
                db_index=True,
                default=False,
                help_text="Selected by sync from the newest 2,000 INBOX messages; browsing never enables AI.",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="labels_known",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
