# Generated by Django 6.0.8 on 2026-09-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0009_message_in_ai_window_message_labels_known"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="in_ai_window",
            field=models.BooleanField(
                db_default=False,
                db_index=True,
                default=False,
                help_text="Selected by sync within the bounded newest-INBOX automation window; browsing never enables AI.",
            ),
        ),
    ]
