# Generated by Django 6.0.8 on 2026-09-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0010_alter_message_in_ai_window"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tab",
            name="label_id",
            field=models.TextField(
                help_text="Gmail's ID for the label pinned by this tab, not a local database ID. Null for legacy query-only tabs without an associated Gmail label.",
                null=True,
                unique=True,
            ),
        ),
    ]
