# Generated by Django 6.0.8 on 2026-09-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0011_tab_label_id_help_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="in_ai_window",
        ),
        migrations.RemoveField(
            model_name="message",
            name="labels_known",
        ),
        migrations.AlterField(
            model_name="message",
            name="labels",
            field=models.JSONField(
                default=list,
                help_text="Cached Gmail label IDs, refreshed by history sync and message/thread detail reads.",
            ),
        ),
    ]
