# Generated by Django 6.0.8 on 2026-09-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0012_demand_loaded_mail"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="importance",
            field=models.FloatField(
                null=True,
                help_text="Jev importance normalized from 0 (lowest) to 1 (highest).",
            ),
        ),
        migrations.AddField(
            model_name="tab",
            name="acceptance_threshold",
            field=models.FloatField(default=0.75, db_default=0.75),
        ),
        migrations.AddField(
            model_name="message",
            name="ai_attempts",
            field=models.PositiveSmallIntegerField(
                db_default=0,
                default=0,
                help_text="Paid classification attempts, including uncertain/interrupted calls. Three total attempts: the initial request plus two retries.",
            ),
        ),
    ]
