# Generated by Django 6.0.8 on 2026-10-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0013_message_ai_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="tab",
            name="feed",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Show full emails one after another, marking each read as it is scrolled into focus.",
            ),
        ),
    ]
