# Generated by Django 6.0.8 on 2026-10-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0014_tab_feed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tab",
            name="feed",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Show full emails one after another; each is marked read and archived once seen.",
            ),
        ),
    ]
