# Generated by Django 6.0.8 on 2026-09-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_workflow_loops"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="retry_at",
            field=models.BigIntegerField(
                db_default=0,
                default=0,
                help_text="Earliest automatic quota retry, in Unix milliseconds; Refresh cannot bypass it.",
            ),
        ),
        migrations.AddField(
            model_name="work",
            name="retry_delay",
            field=models.PositiveIntegerField(
                db_default=0,
                default=0,
                help_text="Previous quota cooldown in seconds, for exponential backoff.",
            ),
        ),
    ]
