# Generated by Django 6.0.8 on 2026-09-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0003_work_retry_at_work_retry_delay"),
    ]

    operations = [
        migrations.AddField(
            model_name="work",
            name="reclassification",
            field=models.JSONField(
                db_default={},
                default=dict,
                help_text="Sync-only reset selection: message_ids and label_ids. Retained through failures until label removal and cache refresh succeed; never exposed in progress.",
            ),
        ),
    ]
