# Generated by Django 6.0.8 on 2026-09-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="recovery_cursor",
            field=models.TextField(
                help_text="History anchor captured before a resumable label rebuild.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="sync_labels",
            field=models.JSONField(
                default=dict,
                db_default={},
                help_text="Uncommitted sync snapshots: message ID to label IDs, or null for deletion. Never authoritative until history catch-up succeeds.",
            ),
        ),
    ]
