# Generated by Django 6.0.8 on 2026-09-14 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_account_recovery_cursor_account_sync_labels"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="recovery_cursor",
        ),
        migrations.RemoveField(
            model_name="account",
            name="sync_labels",
        ),
    ]
