# Generated by Django 6.0.8 on 2026-09-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classifications", "0003_remove_classification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labeldecision",
            name="applied",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="This label was confirmed present in Gmail, either already there or after a successful write. Retained after manual removal to avoid reapplying it; not an indication that the label is currently present.",
            ),
        ),
        migrations.AlterField(
            model_name="labeldecision",
            name="label_id",
            field=models.TextField(
                help_text="Gmail label ID, not a local tab reference. Decisions survive unpinning a tab."
            ),
        ),
        migrations.AlterField(
            model_name="labeldecision",
            name="source",
            field=models.CharField(
                choices=[("sender", "Sender rule"), ("ai", "AI classification")],
                max_length=16,
            ),
        ),
    ]
