# Generated by Django 6.0.8 on 2026-09-12 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classifications", "0004_alter_labeldecision_applied_and_more"),
        ("inbox", "0009_message_in_ai_window_message_labels_known"),
    ]

    operations = [
        migrations.CreateModel(
            name="SenderBackfill",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.EmailField(max_length=254)),
                ("page_token", models.TextField(default="")),
                (
                    "tab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inbox.tab"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tab", "sender"), name="one_sender_backfill"
                    )
                ],
            },
        ),
    ]
