# Generated by Django 6.0.8 on 2026-09-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classifications", "0005_senderbackfill"),
    ]

    operations = [
        migrations.CreateModel(
            name="SenderFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label_id", models.TextField(db_index=True)),
                ("senders", models.JSONField(default=list)),
                ("gmail_id", models.TextField(null=True, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("creating", "Creation needs review"),
                            ("ready", "Installed"),
                            ("failed", "Setup failed; pending retry"),
                            ("conflict", "Changed in Gmail; needs review"),
                        ],
                        default="creating",
                        max_length=16,
                    ),
                ),
            ],
        ),
    ]
