# Generated by Django 6.0.8 on 2026-09-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classifications", "0006_senderfilter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="senderfilter",
            name="gmail_id",
            field=models.TextField(
                help_text="ID returned by Gmail when filter creation succeeds; null until confirmed.",
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="senderfilter",
            name="label_id",
            field=models.TextField(
                db_index=True,
                help_text="Gmail label ID this filter applies; retained after its tab is unpinned.",
            ),
        ),
        migrations.AlterField(
            model_name="senderfilter",
            name="senders",
            field=models.JSONField(
                default=list,
                help_text="Sender email addresses grouped into this filter's Gmail search criteria.",
            ),
        ),
        migrations.AlterField(
            model_name="senderfilter",
            name="state",
            field=models.CharField(
                choices=[
                    ("creating", "Creation needs review"),
                    ("ready", "Installed"),
                    ("failed", "Setup failed; pending retry"),
                    ("conflict", "Changed in Gmail; needs review"),
                ],
                default="creating",
                help_text="Filter setup status: creating records an attempt before contacting Gmail; ready means installed, failed allows retry, and conflict needs owner review. An unfinished creation also needs review before retrying.",
                max_length=16,
            ),
        ),
    ]
