# Generated by Django 6.0.8 on 2026-09-12 11:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("classifications", "0007_senderfilter_field_help_text"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SenderFilter",
        ),
        migrations.DeleteModel(
            name="SenderBackfill",
        ),
    ]
