# Generated by Django 6.0.8 on 2026-09-14 06:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("classifications", "0008_remove_sender_tracking"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="aitracking",
            name="one_tracking_start",
        ),
        migrations.DeleteModel(
            name="AITracking",
        ),
    ]
