# Generated by Django 6.0.8 on 2026-09-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classifications", "0009_remove_ai_tracking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="airequest",
            name="cache_write_tokens",
        ),
        migrations.RemoveField(
            model_name="airequest",
            name="cached_tokens",
        ),
        migrations.RemoveField(
            model_name="airequest",
            name="reasoning",
        ),
        migrations.RemoveField(
            model_name="airequest",
            name="reasoning_tokens",
        ),
        migrations.RemoveField(
            model_name="airequest",
            name="response_id",
        ),
        migrations.AddField(
            model_name="labeldecision",
            name="ai_score",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="labeldecision",
            name="reason",
            field=models.TextField(db_default="", default=""),
        ),
    ]
